config/routes.rb
Rails.application.routes.draw do

  resources :pruebas
  root :to => 'sesiones#login'
  resources :dosificaciones
  resources :pasteurizaciones
  resources :analisisregistros
  #get 'analisis/registros'
  resources :recepciones
  #resources :frascos
  #get 'sesiones/login'
  
  resources :donaciones
  resources :usuarios
  #get 'tipousuarios/inicio'
  #get 'donadoras/inicio'
  #get 'hospitales/inicio'
  #get 'clasificaciones/inicio'
  #get 'areas/inicio'
  resources :enfermedades
  resources :especialidades
  resources :nacionalidades
  resources :medicos
  resources :reciennacidos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  match '/areas' => 'areas#inicio', via: :get, :as => :areas_inicio
  match '/area/nuevo' => 'areas#nuevo', via: :get, :as => :area_nuevo
  match '/area/crear' => 'areas#crear', via: :post, :as => :area_crear
  match '/area/:id/mostrar' => 'areas#mostrar', via: :get, :as => :area_mostrar
  match '/area/:id/editar' => 'areas#editar', via: :get, :as => :area_editar
  match '/area/actualizar' => 'areas#actualizar', via: :patch, :as => :area_actualizar
  match '/area/:id/eliminar' => 'areas#eliminar', via: :delete,:as =>:area_eliminar
  match '/buscar_area' => 'areas#inicio', via: :post, :as => :buscar_area

  match '/clasificaciones' => 'clasificaciones#inicio', via: :get, :as => :clasificaciones_inicio
  match '/clasificacion/nuevo' => 'clasificaciones#nuevo', via: :get, :as => :clasificacion_nuevo
  match '/clasificacion/crear' => 'clasificaciones#crear', via: :post, :as => :clasificacion_crear
  match '/clasificacion/:id/mostrar' => 'clasificaciones#mostrar', via: :get, :as => :clasificacion_mostrar
  match '/clasificacion/:id/editar' => 'clasificaciones#editar', via: :get, :as => :clasificacion_editar
  match '/clasificacion/actualizar' => 'clasificaciones#actualizar', via: :patch, :as => :clasificacion_actualizar
  match '/clasificacion/:id/eliminar' => 'clasificaciones#eliminar', via: :delete,:as =>:clasificacion_eliminar
  match '/buscar_clasificacion' => 'clasificaciones#inicio', via: :post, :as => :buscar_clasificacion

  match '/hospitales' => 'hospitales#inicio', via: :get, :as => :hospitales_inicio
  match '/hospital/nuevo' => 'hospitales#nuevo', via: :get, :as => :hospital_nuevo
  match '/hospital/crear' => 'hospitales#crear', via: :post, :as => :hospital_crear
  match '/hospital/:id/mostrar' => 'hospitales#mostrar', via: :get, :as => :hospital_mostrar
  match '/hospital/:id/editar' => 'hospitales#editar', via: :get, :as => :hospital_editar
  match '/hospital/actualizar' => 'hospitales#actualizar', via: :patch, :as => :hospital_actualizar
  match '/hospital/:id/eliminar' => 'hospitales#eliminar', via: :delete,:as =>:hospital_eliminar
  match '/buscar_hospital' => 'hospitales#inicio', via: :post, :as => :buscar_hospital

  match '/donadoras' => 'donadoras#inicio', via: :get, :as => :donadoras_inicio
  match '/donadora/nuevo' => 'donadoras#nuevo', via: :get, :as => :donadora_nuevo
  match '/donadora/crear' => 'donadoras#crear', via: :post, :as => :donadora_crear
  match '/donadora/:id/mostrar' => 'donadoras#mostrar', via: :get, :as => :donadora_mostrar
  match '/donadora/:id/editar' => 'donadoras#editar', via: :get, :as => :donadora_editar
  match '/donadora/actualizar' => 'donadoras#actualizar', via: :patch, :as => :donadora_actualizar
  match '/donadora/:id/eliminar' => 'donadoras#eliminar', via: :delete,:as =>:donadora_eliminar
  match '/buscar_donadora' => 'donadoras#inicio', via: :post, :as => :buscar_donadora


  match '/tipousuarios' => 'tipousuarios#inicio', via: :get, :as => :tipousuarios_inicio
  match '/tipousuario/nuevo' => 'tipousuarios#nuevo', via: :get, :as => :tipousuario_nuevo
  match '/tipousuario/crear' => 'tipousuarios#crear', via: :post, :as => :tipousuario_crear
  match '/tipousuario/:id/mostrar' => 'tipousuarios#mostrar', via: :get, :as => :tipousuario_mostrar
  match '/tipousuario/:id/editar' => 'tipousuarios#editar', via: :get, :as => :tipousuario_editar
  match '/tipousuario/actualizar' => 'tipousuarios#actualizar', via: :patch, :as => :tipousuario_actualizar
  match '/tipousuario/:id/eliminar' => 'tipousuarios#eliminar', via: :delete,:as =>:tipousuario_eliminar
  match '/buscar_tipousuario' => 'tipousuarios#inicio', via: :post, :as => :buscar_tipousuario

  #rutas de busqueda para los catalogos hechos con scaffold
  match '/buscar_enfermedad' => 'enfermedades#index', via: :post, :as => :buscar_enfermedad
  match '/buscar_especialidad' => 'especialidades#index', via: :post, :as => :buscar_especialidad
  match '/buscar_medico' => 'medicos#index', via: :post, :as => :buscar_medico
  match '/buscar_nacionalidad' => 'nacionalidades#index', via: :post, :as => :buscar_nacionalidad
  match '/buscar_reciennacido' => 'reciennacidos#index', via: :post, :as => :buscar_reciennacido
  match '/buscar_usuario' => 'usuarios#index', via: :post, :as => :buscar_usuario
  match '/buscar_donacion' => 'donaciones#index', via: :post, :as => :buscar_donacion
  match '/buscar_recepcion' => 'recepciones#index', via: :post, :as => :buscar_recepcion

  
  match '/etiqueta/:id/mostrar' => 'etiquetas#mostrar', via: :get, :as => :etiqueta_mostrar
  match '/etiquetadonacion/:id/mostrar' => 'etiquetadonaciones#mostrar', via: :get, :as => :etiquetadonacion_mostrar

  match '/ver_informe' => 'informes#ver_informe', via: :get, :as => :ver_informe
  #match '/frasco/:id/mostrar' => 'frascos#mostrar', via: :get, :as => :frasco_mostrar
  #match '/frasco/:id/veretiqueta' => 'frascos#veretiqueta', via: :get, :as => :frasco_veretiqueta
  #match '/frasco/nuevo' => 'frascos#nuevo', via: :get, :as => :frasco_nuevo
  #match '/frasco/crear' => 'frascos#crear', via: :post, :as => :frasco_crear

  match '/validar_curp_reciennacido' => 'reciennacidos#validar_curp', via: :get, :as => :validar_curp_reciennacido
  match '/validar_curp_donadora' => 'donadoras#validar_curp', via: :get, :as => :validar_curp_donadora

  match '/validar_rfc' => 'usuarios#validar_rfc', via: :get, :as => :validar_rfc_usuario
  match '/validar_curp' => 'usuarios#validar_curp', via: :get, :as => :validar_curp_usuario
  match '/validar_correo' => 'usuarios#validar_correo', via: :get, :as => :validar_correo_usuario

  match '/login' => 'sesiones#login', via: :get, :as => :login
  match '/validar_usuario' => 'sesiones#validar_usuario', via: :post, :as => :validar_usuario

  match '/cerrar_sesion' => 'sesiones#cerrar_sesion', via: :get, :as => :cerrar_sesion
end

app/controllers/recepciones_controller.rb
class RecepcionesController < ApplicationController

before_action :authenticate_laboratorista!
layout 'application_lab'

  before_action :set_recepcion, only: [:show, :edit, :update, :destroy]

  # GET /recepciones
  # GET /recepciones.json
  def index

    values = {}
    if params[:fecha_extraccion].present?
      values[:fecha_extraccion] = params[:fecha_extraccion]
    end 

    @recepciones = Recepcion.where(values).paginate(:page => params[:page], :per_page => 2)
  end

  # GET /recepciones/1
  # GET /recepciones/1.json
  def show
  end

  # GET /recepciones/new
  def new
    @recepcion = Recepcion.new
    @areas = Area.all
    @frascos = Frasco.all
  end

  # GET /recepciones/1/edit
  def edit
    @areas = Area.all
    @frascos = Frasco.all
  end

  # POST /recepciones
  # POST /recepciones.json
  def create
    @recepcion = Recepcion.new(recepcion_params)

    respond_to do |format|
      if @recepcion.save
         
        format.html { redirect_to @recepcion, notice: 'Recepción creada exitosamente.' }
        format.json { render :show, status: :created, location: @recepcion }
      else
        format.html { render :new }
        format.json { render json: @recepcion.errors, status: :unprocessable_entity }
      end
    end

     

  end

  # PATCH/PUT /recepciones/1
  # PATCH/PUT /recepciones/1.json
  def update
    respond_to do |format|
      if @recepcion.update(recepcion_params)
        format.html { redirect_to @recepcion, notice: 'Recepción actualizada exitosamente.' }
        format.json { render :show, status: :ok, location: @recepcion }
      else
        format.html { render :edit }
        format.json { render json: @recepcion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recepciones/1
  # DELETE /recepciones/1.json
  def destroy
    @recepcion.destroy
    respond_to do |format|
      format.html { redirect_to recepciones_url, alert: 'Recepción eliminada exitosamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recepcion
      @recepcion = Recepcion.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def recepcion_params
      params.require(:recepcion).permit(:fecha_extraccion, :cantidad, :frasco_id, :area_id)
    end
end

app/helpers/recepciones_helper.rb
module RecepcionesHelper
end

app/views/recepciones/_form.html.erb
<div class="col-md-12 pt-4">

<%= form_with(model: recepcion, id: 'formulario_recepciones', local: true) do |form| %>
  <% if recepcion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recepcion.errors.count, "error") %> prohibited this recepcion from being saved:</h2>

      <ul>
      <% recepcion.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-row">
        <div class="form-group col-md-6">
          <%= form.label :folio_del_frasco %>
          <%= form.select(:frasco_id, @frascos.collect{ |e| [ e.id]}, {include_blank: 'Seleccionar...'}, :class => "form-control") %> 
       
        </div>
        <div class="form-group col-md-6">
            <%= form.label :Área_id %>
            <%= form.select(:area_id, @areas.collect{ |e| [e.nombre, e.id]}, {include_blank: 'Seleccionar...'}, :class => "form-control") %>             
        </div> 
        
    </div>
    <div class="form-row">
      <div class="form-group col-md-6">
              <%= form.label :fecha_de_extracción %>
          <%= form.date_field :fecha_extraccion, :class => "form-control" %>  
        </div>
        <div class="form-group col-md-6">
             <%= form.label :cantidad %>
             <%= form.text_field :cantidad, :class => "form-control", :placeholder => 'cantidad(ml)'  %>           
        </div> 
    </div>

  <%= form.submit "Guardar", :class => "btng btn" %>
<%= link_to 'Regresar', recepciones_path, :class => "btng btn" %>

  
  
<% end %>

</div>

app/views/recepciones/edit.html.erb
<div class="col-md-12 pb-2 " style="border-bottom: solid 3px #cf3b76; ">
      <h1>Actualizar Recepcion</h1>
</div>

<%= render 'form', recepcion: @recepcion %>

app/views/recepciones/index.html.erb
<div class="col-md-12 mb-4 text-center" >
      <p id="notice"><%= notice %></p>
</div>
<div class="col-md-12 mb-4 text-center" >
      <p id="alert"><%= alert %></p>
</div>

<div class="col-md-12 pb-2 " style="border-bottom: solid 3px #cf3b76; ">
      <h1>Recepciones</h1>
</div>

<div class="col-md-12 pt-4">
    <%= link_to 'Nueva recepción', new_recepcion_path, :class => "btng btn" %>
</div> 

<div class="col-md-12 pt-4">
     <h4>Búsqueda</h4>
  <%= form_tag(buscar_recepcion_path, method: :post, :class => "form-inline") do %>
      <%= date_field_tag 'fecha_extraccion', nil, placeholder: 'Fecha de extracción', :class => "form-control mb-2 mr-sm-2" %>
      
      <button class="search btng btn mb-2"> Buscar</button>
  <% end %>    
</div>

<div class="col-md-12 pt-4 table-responsive">
<table class="table table-hover">
  <thead>
    <tr>
      <th>Fecha de extracción</th>
      <th>Cantidad</th>
      <th>Folio del frasco</th>
      <th>Curp de donadora</th>
      <th>Área</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recepciones.each do |recepcion| %>
      <tr>
        <td><%= recepcion.fecha_extraccion %></td>
        <td><%= recepcion.cantidad %></td>
        <td><%= recepcion.frasco.id %></td>
        <td><%= recepcion.frasco.donacion.donadora.curp %></td>
        <td><%= recepcion.area.nombre %></td>
        
        <td><%= link_to content_tag(:i, nil, class: "mostrar fas fa-eye", :title=> "Mostar"),recepcion %></td>

        <td><%= link_to content_tag(:i, nil, class: "editar fas fa-edit", :title=> "Editar"),edit_recepcion_path(recepcion) %></td>
                   
        <td><%= link_to content_tag(:i, nil, class: "eliminar fas fa-times", :title=> "Eliminar"), recepcion, method: :delete, data: { confirm: '¿Estás seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

</div>
<div class="mx-auto">
  <%= will_paginate @recepciones %>
</div>

app/views/recepciones/new.html.erb
<div class="col-md-12 pb-2 " style="border-bottom: solid 3px #cf3b76; ">
      <h1>Registrar recepción</h1>
</div>

<%= render 'form', recepcion: @recepcion %>

app/views/recepciones/show.html.erb
<div class="col-md-12 mb-4 text-center" >
      <p id="notice"><%= notice %></p>
</div>

<div class="col-md-12 pb-2 " style="border-bottom: solid 3px #cf3b76; ">
      <h1>Recepción</h1>
</div>

<div class="mostrar-contenedor container mt-4 mb-4  p-4 rounded">
  <div class="row p-2">
    <div class="col-6">
      <p class="text-right font-weight-bold">Folio del frasco:</p> 
    </div>
    <div class="col-6">
      <p><%= @recepcion.frasco.id %></p>
    </div>
  </div>

  <div class="row p-2">
    <div class="col-6">
      <p class="text-right font-weight-bold">Curp de la donadora:</p> 
    </div>
    <div class="col-6">
     <p><%= @recepcion.frasco.donacion.donadora.curp %></p>
    </div>
  </div>

  <div class="row p-2">
    <div class="col-6">
      <p class="text-right font-weight-bold">Nombre de la donadora:</p> 
    </div>
    <div class="col-6">
     <p><%= @recepcion.frasco.donacion.donadora.nombre %><%= " "%><%= @recepcion.frasco.donacion.donadora.paterno %><%= " "%><%= @recepcion.frasco.donacion.donadora.materno %></p>
    </div>
  </div>
  
  

  <div class="row p-2">
    <div class="col-6">
      <p class="text-right font-weight-bold">Cantidad:</p> 
    </div>
    <div class="col-6">
      <p><%= @recepcion.cantidad %></p>
    </div>
  </div>

  <div class="row p-2">
    <div class="col-6">
      <p class="text-right font-weight-bold">Fecha de extracción:</p> 
    </div>
    <div class="col-6">
      <p><%= @recepcion.fecha_extraccion %></p>
    </div>
  </div>

  <div class="row p-2">
    <div class="col-6">
      <p class="text-right font-weight-bold">Área:</p> 
    </div>
    <div class="col-6">
      <p><%= @recepcion.area.nombre %></p>
    </div>
  </div>

</div>

<%= link_to 'Editar', edit_recepcion_path(@recepcion), :class => "btng btn mr-2" %>
<%= link_to 'Regresar', recepciones_path, :class => "btng btn mr-2" %>