config/routes.rb
Rails.application.routes.draw do

  resources :pruebas
  root :to => 'sesiones#login'
  resources :dosificaciones
  resources :pasteurizaciones
  resources :analisisregistros
  #get 'analisis/registros'
  resources :recepciones
  #resources :frascos
  #get 'sesiones/login'
  
  resources :donaciones
  resources :usuarios
  #get 'tipousuarios/inicio'
  #get 'donadoras/inicio'
  #get 'hospitales/inicio'
  #get 'clasificaciones/inicio'
  #get 'areas/inicio'
  resources :enfermedades
  resources :especialidades
  resources :nacionalidades
  resources :medicos
  resources :reciennacidos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  match '/areas' => 'areas#inicio', via: :get, :as => :areas_inicio
  match '/area/nuevo' => 'areas#nuevo', via: :get, :as => :area_nuevo
  match '/area/crear' => 'areas#crear', via: :post, :as => :area_crear
  match '/area/:id/mostrar' => 'areas#mostrar', via: :get, :as => :area_mostrar
  match '/area/:id/editar' => 'areas#editar', via: :get, :as => :area_editar
  match '/area/actualizar' => 'areas#actualizar', via: :patch, :as => :area_actualizar
  match '/area/:id/eliminar' => 'areas#eliminar', via: :delete,:as =>:area_eliminar
  match '/buscar_area' => 'areas#inicio', via: :post, :as => :buscar_area

  match '/clasificaciones' => 'clasificaciones#inicio', via: :get, :as => :clasificaciones_inicio
  match '/clasificacion/nuevo' => 'clasificaciones#nuevo', via: :get, :as => :clasificacion_nuevo
  match '/clasificacion/crear' => 'clasificaciones#crear', via: :post, :as => :clasificacion_crear
  match '/clasificacion/:id/mostrar' => 'clasificaciones#mostrar', via: :get, :as => :clasificacion_mostrar
  match '/clasificacion/:id/editar' => 'clasificaciones#editar', via: :get, :as => :clasificacion_editar
  match '/clasificacion/actualizar' => 'clasificaciones#actualizar', via: :patch, :as => :clasificacion_actualizar
  match '/clasificacion/:id/eliminar' => 'clasificaciones#eliminar', via: :delete,:as =>:clasificacion_eliminar
  match '/buscar_clasificacion' => 'clasificaciones#inicio', via: :post, :as => :buscar_clasificacion

  match '/hospitales' => 'hospitales#inicio', via: :get, :as => :hospitales_inicio
  match '/hospital/nuevo' => 'hospitales#nuevo', via: :get, :as => :hospital_nuevo
  match '/hospital/crear' => 'hospitales#crear', via: :post, :as => :hospital_crear
  match '/hospital/:id/mostrar' => 'hospitales#mostrar', via: :get, :as => :hospital_mostrar
  match '/hospital/:id/editar' => 'hospitales#editar', via: :get, :as => :hospital_editar
  match '/hospital/actualizar' => 'hospitales#actualizar', via: :patch, :as => :hospital_actualizar
  match '/hospital/:id/eliminar' => 'hospitales#eliminar', via: :delete,:as =>:hospital_eliminar
  match '/buscar_hospital' => 'hospitales#inicio', via: :post, :as => :buscar_hospital

  match '/donadoras' => 'donadoras#inicio', via: :get, :as => :donadoras_inicio
  match '/donadora/nuevo' => 'donadoras#nuevo', via: :get, :as => :donadora_nuevo
  match '/donadora/crear' => 'donadoras#crear', via: :post, :as => :donadora_crear
  match '/donadora/:id/mostrar' => 'donadoras#mostrar', via: :get, :as => :donadora_mostrar
  match '/donadora/:id/editar' => 'donadoras#editar', via: :get, :as => :donadora_editar
  match '/donadora/actualizar' => 'donadoras#actualizar', via: :patch, :as => :donadora_actualizar
  match '/donadora/:id/eliminar' => 'donadoras#eliminar', via: :delete,:as =>:donadora_eliminar
  match '/buscar_donadora' => 'donadoras#inicio', via: :post, :as => :buscar_donadora


  match '/tipousuarios' => 'tipousuarios#inicio', via: :get, :as => :tipousuarios_inicio
  match '/tipousuario/nuevo' => 'tipousuarios#nuevo', via: :get, :as => :tipousuario_nuevo
  match '/tipousuario/crear' => 'tipousuarios#crear', via: :post, :as => :tipousuario_crear
  match '/tipousuario/:id/mostrar' => 'tipousuarios#mostrar', via: :get, :as => :tipousuario_mostrar
  match '/tipousuario/:id/editar' => 'tipousuarios#editar', via: :get, :as => :tipousuario_editar
  match '/tipousuario/actualizar' => 'tipousuarios#actualizar', via: :patch, :as => :tipousuario_actualizar
  match '/tipousuario/:id/eliminar' => 'tipousuarios#eliminar', via: :delete,:as =>:tipousuario_eliminar
  match '/buscar_tipousuario' => 'tipousuarios#inicio', via: :post, :as => :buscar_tipousuario

  #rutas de busqueda para los catalogos hechos con scaffold
  match '/buscar_enfermedad' => 'enfermedades#index', via: :post, :as => :buscar_enfermedad
  match '/buscar_especialidad' => 'especialidades#index', via: :post, :as => :buscar_especialidad
  match '/buscar_medico' => 'medicos#index', via: :post, :as => :buscar_medico
  match '/buscar_nacionalidad' => 'nacionalidades#index', via: :post, :as => :buscar_nacionalidad
  match '/buscar_reciennacido' => 'reciennacidos#index', via: :post, :as => :buscar_reciennacido
  match '/buscar_usuario' => 'usuarios#index', via: :post, :as => :buscar_usuario
  match '/buscar_donacion' => 'donaciones#index', via: :post, :as => :buscar_donacion
  match '/buscar_recepcion' => 'recepciones#index', via: :post, :as => :buscar_recepcion

  
  match '/etiqueta/:id/mostrar' => 'etiquetas#mostrar', via: :get, :as => :etiqueta_mostrar
  match '/etiquetadonacion/:id/mostrar' => 'etiquetadonaciones#mostrar', via: :get, :as => :etiquetadonacion_mostrar

  match '/ver_informe' => 'informes#ver_informe', via: :get, :as => :ver_informe
  #match '/frasco/:id/mostrar' => 'frascos#mostrar', via: :get, :as => :frasco_mostrar
  #match '/frasco/:id/veretiqueta' => 'frascos#veretiqueta', via: :get, :as => :frasco_veretiqueta
  #match '/frasco/nuevo' => 'frascos#nuevo', via: :get, :as => :frasco_nuevo
  #match '/frasco/crear' => 'frascos#crear', via: :post, :as => :frasco_crear

  match '/validar_curp_reciennacido' => 'reciennacidos#validar_curp', via: :get, :as => :validar_curp_reciennacido
  match '/validar_curp_donadora' => 'donadoras#validar_curp', via: :get, :as => :validar_curp_donadora

  match '/validar_rfc' => 'usuarios#validar_rfc', via: :get, :as => :validar_rfc_usuario
  match '/validar_curp' => 'usuarios#validar_curp', via: :get, :as => :validar_curp_usuario
  match '/validar_correo' => 'usuarios#validar_correo', via: :get, :as => :validar_correo_usuario

  match '/login' => 'sesiones#login', via: :get, :as => :login
  match '/validar_usuario' => 'sesiones#validar_usuario', via: :post, :as => :validar_usuario

  match '/cerrar_sesion' => 'sesiones#cerrar_sesion', via: :get, :as => :cerrar_sesion
end

app/controllers/clasificaciones_controller.rb
class ClasificacionesController < ApplicationController
    before_action :authenticate_admin!

  def inicio
    values = {}
    if params[:nombre].present?
      values[:nombre] = params[:nombre]
    end 
    if params[:color].present?
      values[:color] = params[:color]
    end 
    if params[:consistencia].present?
      values[:consistencia] = params[:consistencia]
    end 
    if params[:proteina].present?
      values[:proteina] = params[:proteina]
    end 
  

    @clasificaciones = Clasificacion.where(values).paginate(:page => params[:page], :per_page => 2)
    
  end

  def nuevo
  	@clasificacion = Clasificacion.new
  end

  def crear
  	@clasificacion = Clasificacion.new(nombre: params[:clasificacion][:nombre], descripcion: params[:clasificacion][:descripcion], color: params[:clasificacion][:color], consistencia: params[:clasificacion][:consistencia], proteina: params[:clasificacion][:proteina], cantidad: params[:clasificacion][:cantidad]) 
	
	respond_to do |format|
		if @clasificacion.save
			format.html{ redirect_to clasificaciones_inicio_path, notice: 'Clasificación creada existosamente.'}
		end
	end		
  end

  def mostrar
  	@clasificacion = Clasificacion.find(params[:id])
  end

  def editar
    @clasificacion =  Clasificacion.find(params[:id])
  end

  def actualizar
    @clasificacion =  Clasificacion.find(params[:clasificacion][:id])

    respond_to do |format|
      if @clasificacion.update(params.require(:clasificacion).permit(:nombre, :descripcion, :color, :consistencia, :proteina, :cantidad))
        format.html{ redirect_to clasificacion_mostrar_path(@clasificacion.id), notice: 'Clasificación actualizada existosamente.'}
      end
    end   
  end

  def eliminar
    @clasificacion = Clasificacion.find(params[:id])
    respond_to do |format|
      if @clasificacion.destroy
        format.html{ redirect_to clasificaciones_inicio_path, alert: 'Clasificación eliminada existosamente.'}
      end
    end 
  end

  rescue_from ActiveRecord::DeleteRestrictionError do |exception|
      redirect_to(clasificaciones_inicio_path, alert: 'Este registro está asociado a un registro, no puedes eliminarlo.')
  end

end

app/helpers/clasificaciones_helper.rb
module ClasificacionesHelper
end

app/views/clasificaciones/_formulario.html.erb
	<div class="form-row">
    	<div class="form-group col-md-6">
           <%= form.label :nombre %>
		<%= form.text_field :nombre, :class => "form-control" %>
		<%= form.hidden_field :id %>       
        </div>
        <div class="form-group col-md-6">
            <%= form.label :descripción %>
			<%= form.text_field :descripcion, :class => "form-control" %>           
        </div> 
    </div>
    <div class="form-row">
    	<div class="form-group col-md-6">
           <%= form.label :color %>
		<%= form.text_field :color, :class => "form-control" %>       
        </div>
        <div class="form-group col-md-6">
            <%= form.label :consistencia %>
		<%= form.text_field :consistencia, :class => "form-control" %>         
        </div> 
    </div>

    <div class="form-row">
    	<div class="form-group col-md-6">
           <%= form.label :proteína %>
		<%= form.text_field :proteina, :class => "form-control" %>     
        </div>
        <div class="form-group col-md-6">
            <%= form.label :cantidad %>
		<%= form.text_field :cantidad, :class => "form-control", :placeholder => 'Ejem: 00.000' %>      
        </div> 
    </div>

	

	<%= form.submit "Guardar", :class => "btng btn" %>
	<%= link_to 'Regresar', clasificaciones_inicio_path, :class => "btng btn" %>

app/views/clasificaciones/editar.html.erb
<div class="col-md-12 pb-2 " style="border-bottom: solid 3px #cf3b76; ">
      <h1>Actualizar clasificación</h1>
</div>

<div class="col-md-12 pt-4">
<%= form_with(model: @clasificacion, id:'formulario_clasificaciones', url: clasificacion_actualizar_path, local: true) do |f|%>

	<%= render 'formulario', form: f %>


<% end %>
</div>	

app/views/clasificaciones/inicio.html.erb
<div class="col-md-12 mb-4 text-center" >
      <p id="notice"><%= notice %></p>
</div>
<div class="col-md-12 mb-4 text-center" >
      <p id="alert"><%= alert %></p>
</div>

<div class="col-md-12 pb-2 " style="border-bottom: solid 3px #cf3b76; ">
      <h1>Clasificaciones</h1>
</div>

<div class="col-md-12 pt-4">
    <%= link_to 'Nueva clasificación', clasificacion_nuevo_path, :class => "btng btn" %>
</div> 

<div class="col-md-12 pt-4">
  <h4>Búsqueda</h4>
  <%= form_tag(buscar_clasificacion_path, method: :post, :class => "form-inline") do %>
      <%= text_field_tag 'nombre', nil, placeholder: 'Nombre', :class => "form-control mb-2 mr-sm-2" %> 
      <%= text_field_tag 'color', nil, placeholder: 'Color', :class => "form-control mb-2 mr-sm-2" %> 
      <%= text_field_tag 'consistencia', nil, placeholder: 'Consistencia', :class => "form-control mb-2 mr-sm-2" %> 
      <%= text_field_tag 'proteina', nil, placeholder: 'Proteína', :class => "form-control mb-2 mr-sm-2" %> 
      <button class="search btng btn mb-2"> Buscar</button>
  <% end %>    
</div>


<div class="col-md-12 pt-4 table-responsive-sm">
<table class="table table-hover">
    <tr>
      <th scope="col">Nombre</th>
      <th scope="col">Descripción</th>
      <th scope="col">Color</th>
      <th scope="col">Consistencia</th>
      <th scope="col">Proteína</th>
      <th scope="col">Cantidad</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clasificaciones.each do |clasificacion| %>
      <tr>
        <td><%= clasificacion.nombre %></td>
        <td><%= clasificacion.descripcion %></td>
        <td><%= clasificacion.color %></td>
        <td><%= clasificacion.consistencia %></td>
        <td><%= clasificacion.proteina %></td>
        <td><%= clasificacion.cantidad %></td>
        <td><%= link_to content_tag(:i, nil, class: "mostrar fas fa-eye", :title=> "Mostrar"),clasificacion_mostrar_path(clasificacion.id) %></td>
        <td><%= link_to content_tag(:i, nil, class: "editar fas fa-edit", :title=> "Editar"),clasificacion_editar_path(clasificacion.id) %></td>         
        <td><%= link_to content_tag(:i, nil, class: "eliminar fas fa-times", :title=> "Eliminar"), clasificacion_eliminar_path(clasificacion.id), method: :delete, data: { confirm: '¿Estás seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<div class="mx-auto">
  <%= will_paginate @clasificaciones %>
</div>

app/views/clasificaciones/mostrar.html.erb
<div class="col-md-12 mb-4 text-center" >
      <p id="notice"><%= notice %></p>
</div>





<div class="col-md-12 pb-2 " style="border-bottom: solid 3px #cf3b76; ">
      <h1>Clasificación</h1>
</div>


<div class="mostrar-contenedor container mt-4 mb-4  p-4 rounded">
  <div class="row p-2">
    <div class="col-6">
      <p class="text-right font-weight-bold">Nombre:</p> 
    </div>
    <div class="col-6">
      <p><%= @clasificacion.nombre %></p>
    </div>
  </div>

  <div class="row p-2">
    <div class="col-6">
      <p class="text-right font-weight-bold">Descripción:</p> 
    </div>
    <div class="col-6">
      <p><%= @clasificacion.descripcion%></p>
    </div>
  </div>

  <div class="row p-2">
    <div class="col-6">
      <p class="text-right font-weight-bold">Color:</p> 
    </div>
    <div class="col-6">
      <p><%= @clasificacion.color %></p>
    </div>
  </div>

  <div class="row p-2">
    <div class="col-6">
      <p class="text-right font-weight-bold">Consitencia:</p> 
    </div>
    <div class="col-6">
      <p><%= @clasificacion.consistencia %></p>
    </div>
  </div>

  <div class="row p-2">
    <div class="col-6">
      <p class="text-right font-weight-bold">Proteína:</p> 
    </div>
    <div class="col-6">
      <p><%= @clasificacion.proteina %></p>
    </div>
  </div>

  <div class="row p-2">
    <div class="col-6">
      <p class="text-right font-weight-bold">Cantidad:</p> 
    </div>
    <div class="col-6">
      <p> <%= @clasificacion.cantidad %></p>
    </div>
  </div>
</div>


<%= link_to 'Regesar', clasificaciones_inicio_path, :class => "btng btn" %>

app/views/clasificaciones/nuevo.html.erb
<div class="col-md-12 pb-2 " style="border-bottom: solid 3px #cf3b76; ">
      <h1>Registrar clasificación</h1>
</div>


<div class="col-md-12 pt-4">
<%= form_with(model: @clasificacion,  id:'formulario_clasificaciones', url: clasificacion_crear_path, local:true) do |f|%>

	<%= render 'formulario', form: f %>


<% end %>	
</div>